# ==============================================================================
# Final Evaluation: Dual-Track Architecture vs. Global Baseline Model
# Generates Figure 6: ROC Comparison (A), DCA (B), and NRI/IDI (C)
# ==============================================================================

import os
import pandas as pd
import numpy as np
import matplotlib

matplotlib.use('Agg')  # Force backend to prevent threading issues
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
import warnings

warnings.filterwarnings('ignore')

# ======================================================================
# 1. Path Configuration
# ======================================================================
# Seamlessly links to the output generated by the External Validation script
INPUT_DATA_PATH = "./output/3_External_Validation/Data_Aligned_Probabilities_Summary.xlsx"
OUTPUT_DIR = "./output/4_Dual_Track_vs_Global_Comparison_Fig6/"

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ======================================================================
# 2. SCI-Standard Plot Settings (Times New Roman)
# ======================================================================
def set_scientific_style():
    plt.rcParams.update(plt.rcParamsDefault)
    FONT_FAMILY = "Times New Roman"
    FONT_SIZE = 16
    config = {
        "font.family": "serif", "font.serif": [FONT_FAMILY], "font.size": FONT_SIZE,
        "font.weight": "bold", "pdf.fonttype": 42, "ps.fonttype": 42,
        "figure.figsize": (8, 6), "figure.dpi": 300, "axes.linewidth": 2.0,
        "axes.labelsize": FONT_SIZE + 2, "axes.labelweight": "bold", "axes.titleweight": "bold",
        "xtick.labelsize": FONT_SIZE, "ytick.labelsize": FONT_SIZE, "xtick.direction": "in",
        "ytick.direction": "in", "axes.unicode_minus": False, "xtick.major.width": 2.0,
        "ytick.major.width": 2.0, "xtick.major.size": 6, "ytick.major.size": 6,
        "axes.spines.top": False, "axes.spines.right": False
    }
    plt.rcParams.update(config)


set_scientific_style()


def bold_ticks(ax):
    for label in ax.get_xticklabels() + ax.get_yticklabels():
        label.set_fontweight('bold')


# ======================================================================
# 3. Main Execution & Data Loading
# ======================================================================
if __name__ == "__main__":
    print("-" * 60)
    print("Initiating Final Comparison: Dual-Track vs Global Baseline Model")

    if not os.path.exists(INPUT_DATA_PATH):
        print(f"[Error] Required dataset not found at {INPUT_DATA_PATH}.")
        print("Please run the External Validation script first.")
        exit()

    df = pd.read_excel(INPUT_DATA_PATH)
    df = df.dropna(subset=['CVD-Label', 'Predicted_CVD_Prob', 'Global_CVD_Prob'])

    y_true = df['CVD-Label'].values
    prob_dual = df['Predicted_CVD_Prob'].values
    prob_global = df['Global_CVD_Prob'].values

    # ======================================================================
    # 4. Figure 6A: ROC Curve Comparison
    # ======================================================================
    print("Generating Figure 6A: ROC Comparison...")
    fpr_d, tpr_d, _ = roc_curve(y_true, prob_dual)
    auc_d = auc(fpr_d, tpr_d)

    fpr_g, tpr_g, _ = roc_curve(y_true, prob_global)
    auc_g = auc(fpr_g, tpr_g)

    fig, ax = plt.subplots()
    ax.plot(fpr_d, tpr_d, color='#D8383A', lw=3, label=f'Dual-Track Model (AUC={auc_d:.3f})')
    ax.plot(fpr_g, tpr_g, color='#1F77B4', lw=2.5, linestyle='--', label=f'Global Model (AUC={auc_g:.3f})')
    ax.plot([0, 1], [0, 1], color='grey', lw=2, linestyle=':')

    ax.set_xlim([-0.05, 1.05]);
    ax.set_ylim([-0.05, 1.05])
    ax.set_xlabel('False Positive Rate');
    ax.set_ylabel('True Positive Rate')
    ax.set_title('Figure 6A: ROC Comparison')
    ax.legend(loc="lower right", frameon=False)
    bold_ticks(ax)

    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "Figure_6A_ROC_Comparison.pdf"), bbox_inches='tight')
    plt.close(fig)

    # ======================================================================
    # 5. Figure 6B: Decision Curve Analysis (DCA) Comparison
    # ======================================================================
    print("Generating Figure 6B: DCA Comparison...")
    thresh_dca = np.arange(0.01, 0.61, 0.01)
    n = len(y_true)
    nb_dual, nb_global, nb_all = [], [], []

    for t in thresh_dca:
        yp_d = (prob_dual >= t).astype(int)
        tp_d = np.sum((yp_d == 1) & (y_true == 1))
        fp_d = np.sum((yp_d == 1) & (y_true == 0))
        nb_dual.append((tp_d / n) - (fp_d / n) * (t / (1 - t)))

        yp_g = (prob_global >= t).astype(int)
        tp_g = np.sum((yp_g == 1) & (y_true == 1))
        fp_g = np.sum((yp_g == 1) & (y_true == 0))
        nb_global.append((tp_g / n) - (fp_g / n) * (t / (1 - t)))

        nb_all.append((np.sum(y_true == 1) / n) - (np.sum(y_true == 0) / n) * (t / (1 - t)))

    fig, ax = plt.subplots()
    ax.plot(thresh_dca, nb_dual, color='#D8383A', lw=3, label='Dual-Track Model')
    ax.plot(thresh_dca, nb_global, color='#1F77B4', lw=2.5, linestyle='--', label='Global Model')
    ax.plot(thresh_dca, nb_all, color='grey', lw=2, linestyle='-', label='Treat All')
    ax.plot([0, 1], [0, 0], color='black', lw=2, linestyle='-', label='Treat None')

    ax.set_xlim([0, 0.6])
    max_y = max(max(nb_dual), max(nb_global), max(nb_all))
    ax.set_ylim([-0.05, max_y + 0.05])

    ax.set_xlabel('Threshold Probability');
    ax.set_ylabel('Net Benefit')
    ax.set_title('Figure 6B: Decision Curve Analysis')
    ax.legend(loc="upper right", frameon=False)
    bold_ticks(ax)

    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "Figure_6B_DCA_Comparison.pdf"), bbox_inches='tight')
    plt.close(fig)

    # ======================================================================
    # 6. NRI and IDI Calculation
    # ======================================================================
    print("Calculating Continuous NRI and IDI Metrics...")
    event_mask = (y_true == 1)
    nonevent_mask = (y_true == 0)

    up_events = np.sum(prob_dual[event_mask] > prob_global[event_mask])
    down_events = np.sum(prob_dual[event_mask] < prob_global[event_mask])
    nri_event = (up_events - down_events) / np.sum(event_mask)

    up_nonevents = np.sum(prob_dual[nonevent_mask] > prob_global[nonevent_mask])
    down_nonevents = np.sum(prob_dual[nonevent_mask] < prob_global[nonevent_mask])
    nri_nonevent = (down_nonevents - up_nonevents) / np.sum(nonevent_mask)

    nri_total = nri_event + nri_nonevent

    idi_event = np.mean(prob_dual[event_mask]) - np.mean(prob_global[event_mask])
    idi_nonevent = np.mean(prob_dual[nonevent_mask]) - np.mean(prob_global[nonevent_mask])
    idi_total = idi_event - idi_nonevent

    # ======================================================================
    # 7. Figure 6C: Reclassification Improvement Bar Chart
    # ======================================================================
    print("Generating Figure 6C: NRI/IDI Bar Chart...")

    metrics = ['NRI\n(Event)', 'NRI\n(Non-event)', 'Total\nNRI', 'Total\nIDI']
    values = [nri_event, nri_nonevent, nri_total, idi_total]
    colors = ['#FF9896', '#98DF8A', '#D62728', '#2CA02C']

    fig, ax = plt.subplots(figsize=(7, 6))
    bars = ax.bar(metrics, values, color=colors, edgecolor='black', linewidth=1.5, width=0.6)

    # Dynamic padding for Y-axis to prevent text overlap
    min_val = min(values)
    max_val = max(values)
    ax.set_ylim([min_val - 0.04, max_val + 0.04])

    ax.axhline(0, color='black', lw=1.5)
    ax.set_ylabel('Improvement Score')
    ax.set_title('Figure 6C: Reclassification Improvement')

    for bar in bars:
        yval = bar.get_height()
        offset = 0.003 if yval >= 0 else -0.003
        ax.text(bar.get_x() + bar.get_width() / 2, yval + offset, f'{yval:.3f}',
                ha='center', va='bottom' if yval >= 0 else 'top', fontweight='bold', fontsize=14)

    bold_ticks(ax)

    plt.tight_layout()
    plt.savefig(os.path.join(OUTPUT_DIR, "Figure_6C_NRI_IDI_Bar.pdf"), bbox_inches='tight')
    plt.close(fig)

    print("-" * 60)
    print("🎉 Pipeline executed successfully! High-quality PDFs generated for Figure 6.")